#pragma once

#define SPAWNRATE_SET 40

#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 640


#define PLAYER_SPEED 4
#define ENEMY_SPEED 2
#define BULLET_SPEED 10
#define ENEMY_BULLET_SPEED 3
#define PENGUIN_JUMP_SET 8

#define RELOAD_TIME 15

#define FPS 60
#define FRAME_TARGET_TIME (1000/FPS)